import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { UIProviders } from './context/nextui-provider';
import Toaster from '@/app/ui/toast';
import QRProvider from './context/query-client-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <UIProviders>
          <QRProvider>{children}</QRProvider>
        </UIProviders>
        <Toaster />
      </body>
    </html>
  );
}
